[workspace]
members = ["antenna", "antenna_wasm_gen", "antenna_codegen", "antenna_server", "antenna_core", "example/simple-group-chat/server"]
resolver = "2"

[workspace.package]
rust-version = "1.89.0"
