[package]
name = "antenna_core"
version = "0.1.0"
edition = "2024"
rust-version.workspace = true

[dependencies]
webrtc = "0.14.0"
serde = { version = "1.0.228", features = ["derive"] }
bytes = "1.11.0"
uuid = { version = "1.19.0", features = ["serde", "v4", "js"] }
serde_bytes = "0.11.19"
