[package]
name = "antenna"
version = "0.1.0"
edition = "2024"

[dependencies]
antenna_core = { path = "../antenna_core" }
antenna_wasm_gen = { path = "../antenna_wasm_gen", optional = true }
antenna_server = { path = "../antenna_server", optional = true }
antenna_codegen = { path = "../antenna_codegen" }

[features]
default = []
server = ["dep:antenna_server"]
client = ["dep:antenna_wasm_gen"]
full = ["server", "client"]
