[package]
name = "antenna"
version = "0.1.0"
edition = "2024"

[dependencies]
antenna_core = { path = "../antenna_core" }
antenna_wasm_gen = { path = "../antenna_wasm_gen" }
antenna_server = { path = "../antenna_server" }
antenna_codegen = { path = "../antenna_codegen" }
