[package]
name = "antenna-cli"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "cargo-antenna" 
path = "src/main.rs"

[dependencies]
clap = { workspace = true }
anyhow = { workspace = true }
colored = { workspace = true }
dialoguer = { workspace = true }
